<a href="https://colab.research.google.com/github/shauryyamishra/Transformers_HuggingFace_SentimentAnalysis/blob/main/Hug_Trans_NLP_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install "transformers[sentencepiece]"


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 18.9 MB/s eta 0:00:00


In [ ]:
!pip install transformers   

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 37.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 11.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 30.2 MB/s eta 0:00:00


In [ ]:
import transformers


In [ ]:
from transformers import pipeline

In [ ]:
classifier= pipeline('sentiment-analysis')
classifier([
    'yo! what a fire day!',
    'this day is not good'
])

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9983503818511963},
 {'label': 'NEGATIVE', 'score': 0.9997859597206116}]

In [ ]:
from transformers import AutoTokenizer

In [ ]:
checkpoint  = 'bert-base-uncased'
tokenizer= AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
raw_inputs=  [ 'yo! what a fire day!',
    'this day is not good']
inputs=tokenizer(raw_inputs,padding=True,truncation=True,return_tensors='tf')
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[  101, 10930,   999,  2054,  1037,  2543,  2154,   999,   102],
       [  101,  2023,  2154,  2003,  2025,  2204,   102,     0,     0]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0]], dtype=int32)>}
